version: "3.7"
volumes:
  postgresql_data:
    driver: local

services:
  web:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    command: gunicorn newsfeedproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
       - ./source/newsfeedproject:/usr/src/app
    expose:
      - "8000"
    env_file:
      ./.env.prod
    depends_on:
      - db
  db:
    build: ./docker/postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      ./.env.prod.db
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - web
